[tool.poetry]
name = "finary-uapi"
version = "0.1.6"
description = "Finary API client and command line tool to interact with your Finary account."
authors = ["lasconic <lasconic@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [{include = "finary_uapi"}]

[tool.poetry.dependencies]
python = "^3.10"
docopt = "^0.6.2"
fuzzywuzzy = {version = "^0.18.0", extras = ["speedup"]}
requests = "^2.30.0"

[tool.poetry.group.dev.dependencies]
black = "23.10.0"
flake8 = "6.1.0"
mypy = "1.6.1"
pdoc3 = "0.10.0"
pydocstyle = "6.3.0"
pytest = "7.4.2"
pytest-cov = "4.1.0"
pytest-dependency = "0.5.1"
responses = "0.23.3"
types-requests = "2.31.0.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
